library volt;

import 'dart:async';
import 'dart:convert';
import 'dart:isolate';
import 'dart:math';
import 'dart:typed_data';
import 'package:http/http.dart' as http;
import 'package:logging/logging.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

part 'src/volt.dart';

// Core
part 'src/core/web/_ws_client.dart';
part 'src/core/web/http/_http_client.dart';
part 'src/core/web/http/_http_handler.dart';
part 'src/core/web/http/http_request.dart';
part 'src/core/web/http/http_response.dart';
part 'src/core/_http_endpoints.dart';
part 'src/core/_event_controller.dart';
part 'src/core/_event_handler.dart';
part 'src/core/ulid.dart';
part 'src/core/ulid_entity.dart';
part 'src/core/event.dart';

// Internal
part 'src/internal/cache.dart';
part 'src/internal/client_options.dart';

// Events
part 'src/events/ready.dart';
part 'src/events/message_received.dart';
part 'src/events/channel_start_typing.dart';
part 'src/events/channel_stop_typing.dart';

// Models
part 'src/models/node_info.dart';
part 'src/models/member.dart';
part 'src/models/relationship.dart';
part 'src/models/ban.dart';
part 'src/models/message/message.dart';
part 'src/models/message/deleted_message.dart';
part 'src/models/message/message_query_data.dart';
part 'src/models/message/message_poll_data.dart';
part 'src/models/role/role.dart';
part 'src/models/role/role_permissions.dart';
part 'src/models/category.dart';
part 'src/models/server/server.dart';
part 'src/models/server/server_flags.dart';
part 'src/models/server/system_messages.dart';
part 'src/models/cache/cacheable_server.dart';
part 'src/models/cache/cacheable_channel.dart';
part 'src/models/cache/cacheable_user.dart';
part 'src/models/cache/cacheable_member.dart';
part 'src/models/cache/cacheable_message.dart';
part 'src/models/cache/internal/_cacheable_profile.dart';
part 'src/models/cache/internal/_cacheable_self_user.dart';
part 'src/models/cache/cacheable_role.dart';
part 'src/models/base/base_text_channel.dart';
part 'src/models/base/base_server.dart';
part 'src/models/base/base_voice_channel.dart';
part 'src/models/base/base_user.dart';
part 'src/models/base/base_role.dart';
part 'src/models/base/base_member.dart';
part 'src/models/base/base_message.dart';
part 'src/models/attachment/attachment.dart';
part 'src/models/attachment/attachment_metadata.dart';
part 'src/models/permissions/permissions.dart';
part 'src/models/permissions/channel_permissions.dart';
part 'src/models/permissions/server_permissions.dart';
part 'src/models/permissions/user_permissions.dart';
part 'src/models/permissions/role_permissions_overrides.dart';
part 'src/models/channel/channel.dart';
part 'src/models/channel/server_channel.dart';
part 'src/models/channel/server_text_channel.dart';
part 'src/models/channel/dm_channel.dart';
part 'src/models/channel/group.dart';
part 'src/models/channel/voice_channel.dart';
part 'src/models/channel/text_channel.dart';
part 'src/models/channel/undefined_channel.dart';
part 'src/models/invite/invite.dart';
part 'src/models/invite/partial_invite.dart';
part 'src/models/invite/invite_info.dart';
part 'src/models/user/user.dart';
part 'src/models/user/banned_user.dart';
part 'src/models/user/self_user.dart';
part 'src/models/user/bot_user.dart';
part 'src/models/user/user_profile.dart';
part 'src/models/user/user_flags.dart';
part 'src/models/user/user_badges.dart';

// Interfaces
part 'src/interfaces/disposable.dart';
part 'src/interfaces/builder.dart';
part 'src/interfaces/cacheable.dart';
part 'src/interfaces/sendible.dart';
part 'src/interfaces/mentionable.dart';
part 'src/interfaces/convertable.dart';
part 'src/interfaces/enum.dart';

// Utils
part 'src/utils/builders/message_builder.dart';
part 'src/utils/builders/message_edit_builder.dart';
part 'src/utils/builders/message_poll_builder.dart';
part 'src/utils/builders/fetch_messages_query_builder.dart';
part 'src/utils/builders/search_messages_query_builder.dart';
part 'src/utils/builders/user_permissions_builder.dart';
part 'src/utils/builders/server_permissions_builder.dart';
part 'src/utils/builders/channel_edit_builder.dart';
part 'src/utils/builders/channel_permissions_builder.dart';
part 'src/utils/builders/user_edit_builder.dart';
part 'src/utils/builders/role_channel_permissions_builder.dart';
part 'src/utils/builders/default_channel_permissions_builder.dart';
part 'src/utils/builders/server_channel_builder.dart';
part 'src/utils/builders/member_edit_builder.dart';
part 'src/utils/builders/ban_builder.dart';
part 'src/utils/builders/permissions_builder.dart';
part 'src/utils/extensions/ulid_extension.dart';
part 'src/utils/flags_utils.dart';
part 'src/utils/_iter_utils.dart';
